auth/auth.go
auth/checker_login.go
document/bucketS3.go
go.mod
graphql/health.go
graphql/info.go
graphql/medical_info.go
graphql/onboarding.go
graphql/patient_appointment.go
test/checker_login_test.go

Add graphql Onboarding
Add graphql Appointment
Add function bucket s3
Add function check if you are log

Onboarding lib

---

appointment/book_appointment.go
appointment/delete_rdv.go
appointment/edit_doctor_appointment.go
appointment/edit_rdv.go
auth/register.go
auth/reset_password.go
go.mod
go.sum
graphql/generated.go
graphql/genqlient.graphql
graphql/schema.graphql
graphql/server/generated.go
graphql/server/model/models_gen.go
graphql/server/schema.resolvers.go
medical_folder/create_medical_info.go
medical_folder/delete_medical_info.go
medical_folder/edit_medical_info.go
medical_folder/get_medical_info.go
medicament/create_medicament.go
medicament/get_medicament.go

Ajout de fonctionnalitées : 
- Medicament
- Medical Folder
- Onboarding Doctor

feat(onboarding): add function for the new onboarding

---

appointment/create_rdv.go
dashboard/get_patient.go
document/bucketS3.go
document/delete_document.go
document/favorite_document.go
document/get_document.go
document/update_document.go
graphql/schema.graphql
graphql/server/generated.go
graphql/server/schema.resolvers.go
medical_folder/create_medical_info.go
medical_folder/get_medical_info.go
medicament/create_medicament.go
medicament/get_medicament.go
slot/create_slot.go
slot/delete_slot.go

Document :
- Get document
- Get all document
- update document
- add favorite document
- Delete favorite
- delete document
Slot :
- Create Slot
- Delete Slot

fix(rdv): fix error update doctor

---

document/favorite_document.go
document/upload_document.go
graphql/server/schema.resolvers.go
slot/create_slot.go
slot/delete_slot.go
slot/get_slot.go

Fix issue on slot part and document

fix(edgarlib): fix  issue on slot part and document part

---

dashboard/get_patient.go
medical_folder/create_medical_info.go

Correction Get Patient
Now get only patient in the list
Correction Medical Folder
Now error print if you try to create medical folder, but is it already exist

fix(dashboard): disable acces to an account

---

dashboard/get_patient.go

Fix error loop for for the check id in get patient by id

fix(dashboard): boucle check id is present in the table of doctor

---

appointment/book_appointment.go
appointment/cancel_rdv.go
appointment/create_rdv.go
appointment/delete_rdv.go
appointment/edit_doctor_appointment.go
appointment/edit_rdv.go
appointment/get_doctor_appointment.go
appointment/get_rdv.go
appointment/get_rdv_patient.go
appointment/get_waiting_review.go
appointment/valide_rdv.go
auth/doctor.go
graphql/generated.go
graphql/genqlient.graphql
graphql/schema.graphql
graphql/server/generated.go
graphql/server/model/models_gen.go
graphql/server/schema.resolvers.go
slot/create_slot.go
slot/get_slot.go

Fix get rdv 
Add status appointment
Add gestion pre diagnostic

feat(doctor): get one doctor or all function

---

appointment/edit_doctor_appointment.go
appointment/valide_rdv.go
medical_folder/create_medical_info.go
medical_folder/edit_medical_info.go

* fix(rdv): error when i try to book an appointment, checking the appointment is real
* fix(rebase): remove duplicata code
* fix(onboarding): change height and weight

Fix rdv (#42)

---

appointment/edit_doctor_appointment.go
appointment/edit_rdv.go
medical_folder/create_medical_info.go
treatment/create_treatment.go
treatment/delete_treatment.go
treatment/edit_treatment.go
treatment/get_treatment.go

feat(treatment): add part of treatment not finish yet

---

dashboard/get_patient.go
medical_folder/create_medical_info.go

Correction error get all patient from the doctor in dashboard, change id of medical folder by the id of the patient

fix(dashboard): change which id is use to get medical folder

---

appointment/book_appointment.go
appointment/create_rdv.go
appointment/delete_rdv.go
appointment/edit_doctor_appointment.go
appointment/edit_rdv.go
appointment/get_waiting_review.go
chat/add_message_chat.go
chat/create_chat.go
chat/get_chat.go
dashboard/create_patient.go
dashboard/delete_patient.go
document/bucketS3.go
document/delete_document.go
document/generate_url.go
document/get_document.go
document/upload_document.go
follow_treatment/delete_follow_up.go
follow_treatment/follow_up_treatment.go
graphql/generated.go
graphql/genqlient.graphql
graphql/schema.graphql
graphql/server/generated.go
graphql/server/model/models_gen.go
graphql/server/schema.resolvers.go
medical_folder/create_medical_info.go
medical_folder/delete_medical_info.go
slot/create_slot.go
slot/delete_slot.go

Add feature messagerie
Add feature privatisation

Add feature of privatisation + messagerie

---

auth/reset_password.go
document/bucketS3.go
document/generate_url.go
document/get_document.go

* fix(compilation): missing update reset password
* fix(doc): modify time
* fix(document): modify privatisation function for s3

Messagerie (#91)

---

appointment/edit_rdv.go
slot/delete_slot.go

fix error : 
- Appointment not found when deleting it
- Bad slot status
- Bad session id when updating an appointment
- Don’t find the slot

fix(appointment): fix slot delete, rdv delete

---

appointment/delete_rdv.go

Fix error : 
- Bad implementation of appointment cancelling

fix(appointment): change delete, now change status and create new slot

---

appointment/book_appointment.go
appointment/cancel_rdv.go
appointment/delete_rdv.go
appointment/edit_doctor_appointment.go
appointment/edit_rdv.go
appointment/valide_rdv.go
chat/create_chat.go
graphql/generated.go
graphql/genqlient.graphql
graphql/schema.graphql
graphql/server/generated.go
graphql/server/model/models_gen.go
graphql/server/schema.resolvers.go

* fix(chat): add update patient ids
* fix(prediagnostic): add condition to create new slot

Fix error route (#112)

---

appointment/valide_rdv.go
medical_folder/edit_medical_info.go

* fix(chat): add update patient ids
* fix(prediagnostic): add condition to create new slot

Fix error route (#112) (#115)

---

auth/auth.go
auth/save_code.go
auth/save_code_test.go
black_list/edit_token.go
graphql/generated.go
graphql/genqlient.graphql
graphql/schema.graphql
graphql/server/generated.go
graphql/server/model/models_gen.go
graphql/server/schema.resolvers.go

Add feature creation of backup code + test

feat(save_code): add function + test for creation of backup code

---

auth/login_2fa_email.go
auth/login_2fa_email_test.go
auth/login_2fa_save_code.go
auth/login_2fa_save_code_test.go
auth/login_2fa_third_party.go
auth/login_2fa_third_party_test.go
auth/save_code.go
auth/save_code_test.go
auth/send_code_2fa_email.go
auth/send_code_2fa_email_test.go
auth/update_password.go
auth/update_password_test.go
double_auth/add_trust_device_test.go
double_auth/double_auth_app_tier.go
double_auth/double_auth_app_tier_test.go
double_auth/get_device_connect.go
double_auth/update_device_connect.go
double_auth/update_device_connect_test.go
go.mod
go.sum
graphql/generated_client.go
graphql/queries.graphql
graphql/schema.graphql
graphql/server/generated.go
graphql/server/schema.resolvers.go

Add Login 2fa for third party / email / backupcode
Add function to change password
Add unit test
Fix doubleAuthThirdParty

feat(2fa_aut): add 2fa method log email + update password

---

double_auth/double_auth_mobile.go

Quickfix Missing management null list

fix(2fa_mobile): missing update TrustList

---

appointment/book_appointment_test.go
auth/utils/connected_device_middleware.go
dashboard/create_patient_test.go
dashboard/get_patient_test.go
graphql/generated_client.go
graphql/model/models_gen.go
graphql/queries.graphql
graphql/schema.graphql
graphql/server/generated.go
graphql/server/schema.resolvers.go
medical_folder/new_create_medical_folder.go
medical_folder/new_create_medical_folder_test.go
medical_folder/new_delete_medical_folder_test.go
medical_folder/new_edit_medical_folder_test.go
medical_folder/new_get_medical_folder_test.go
ordonnance/generate_ordonnance_test.go
ordonnance/get_ordonnance_test.go
treatment/create_treatment.go
treatment/create_treatment_test.go
treatment/delete_treatment.go
treatment/delete_treatment_test.go
treatment/edit_treatment.go
treatment/edit_treatment_test.go
treatment/get_treatment_test.go

Modification Structure medical Antecedent
Edit GetBrowser

fix(MedicalAntecedent): change structure Medicine add 2 variable

---

auth/utils/connected_device_middleware.go

Quick fix function getBrowser, change place of check App edgar

fix(getBrowser): change place of check edgar app in first

---

auth/missing_password.go
auth/utils/connected_device_middleware.go
dashboard/get_patient.go
graphql/server/schema.resolvers.go

Quick fix lower car + change status on missing password and get patient + change get slot return only opened appointment

fix(error): fix error get slot, change status + change getbrowser case

---

medical_folder/new_create_medical_folder.go
treatment/edit_treatment.go
treatment/edit_treatment_test.go

Remove period length condition <= 0 and modify edit period remove id medical antecedent

fix(medical_antecedent): fix condition period length remove

---

graphql/server/schema.resolvers.go
treatment/edit_treatment.go
treatment/edit_treatment_test.go

FIx edit treatment : 
- editing comment 
- editing medicine ID
Fix return

fix(treatment): fix error no editing comment and medicine

---

medical_folder/new_create_medical_folder_test.go
treatment/create_treatment.go
treatment/create_treatment_test.go

Fix add treatment error add medicine on list

fix(treatment): fix creation medicine part, put on unique treatment

---

graphql/server/schema.resolvers.go
treatment/edit_treatment_test.go

fix(graphql): fix update db treatment

---

auth/missing_password.go

fix(email): modify url past on email, change depend of user

---

auth/missing_password.go

quick fix url remove type on url

fix(email): remove type to url

---

treatment/create_treatment.go
treatment/create_treatment_test.go
treatment/edit_treatment.go
treatment/edit_treatment_test.go

Fix error 400 edit treatment when missing periodLength and periodUnit
FIx error comment duplicate on add
Fix error edit periodLength duplic

fix(treatment): fix error with comment duplicate

---

graphql/server/schema.resolvers.go

fix(slot): modify get slots return all expect canceled
